---
url: https://www.emfink.net 
baseurl: /CivilProcedure 
title: Civil Procedure 
description:  # leave blank for no description 
last_updated: 23 August 2020

name: Civil Procedure 
author: Eric M. Fink 
institution: Elon Law School
street: 201 North Greene Street
city: Greensboro
state: North Carolina
zip: '27401'
email: efink@elon.edu
phone: 336-279-9334

collections: 
  cases: 
    output: true 
  exams:
    output: true
  notes: 
    output: true 
  outlines:
    output: true
  problems:
    output: true 
  questions:
    output: true
  readings: 
    output: true 
  statutes: 
    output: true 
  visuals:
    output: true


# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
remote_theme: luckyjimjd/lj-folio

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
